### ISSUE TITLE
Window Buttons are not visible in class library

### ISSUE THREAD

**Issue by ShrlAlgo** [russkyc/modern-controls-wpf#31]
I am working for revit plugins development,here's the result
![image](https://github.com/russkyc/modern-controls-wpf/assets/40654941/51537ea7-8285-471d-8b9e-33fb9211dbba)

**Comment by ShrlAlgo** [comment]
![image](https://github.com/russkyc/modern-controls-wpf/assets/40654941/66fef5a3-8ffe-4546-8854-43ac61b65fd6)

**Comment by russkyc** [comment]
Hi @sherlockforrest , have you by any chance tried to embed the resource inside the `App.xaml` instead of the window? If you are using the latest version, it should be implemented this way:

```xaml
    <Application.Resources>
        <!--  ModernControls WPF, change the base theme and color theme according to your liking  -->
        <styles:ModernControlsWpf BaseTheme="Dark" ColorTheme="Green" />
    </Application.Resources>
```

Let me know if you still face the same issue after, I'll also try to reproduce this

**Comment by ShrlAlgo** [comment]
@russkyc Thank you for your reply,There is no `App.xaml` for the Class Library Project. XAML, so I put the resource in the window resources, and I fixed the problem, I changed the order in which in the `ResourceDictionary.MergedDictionaries` .put `Generic.xaml `at the end,now it works;
```
    <Window.Resources>
        <ResourceDictionary>
            <ResourceDictionary.MergedDictionaries>
                <ResourceDictionary Source="pack://application:,,,/Russkyc.ModernControls.WPF;component/Themes/BaseThemes/Light.xaml" />
                <ResourceDictionary Source="pack://application:,,,/Russkyc.ModernControls.WPF;component/Themes/ColorThemes/Blue.xaml" />
                <ResourceDictionary Source="pack://application:,,,/Russkyc.ModernControls.WPF;component/Themes/Generic.xaml" />
            </ResourceDictionary.MergedDictionaries>
        </ResourceDictionary>
        <!--<styles:ModernControlsWpf BaseTheme="Dark" ColorTheme="Blue" />-->
    </Window.Resources>
```
![image](https://github.com/russkyc/modern-controls-wpf/assets/40654941/3a4a7a95-cc33-4c99-aec9-7ca1ef7f220f)
